---
    name: Unified Dogfooding scans
    on:
      schedule:
        # Run the workflow every day at 04:00 UTC
        - cron: '0 4 * * *'
      workflow_dispatch:

    jobs:
      build:
        runs-on: github-ubuntu-latest-s
        name: Build and run shadow scans
        permissions:
          id-token: write
          contents: write
        steps:
          - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
            with:
              version: 2026.2.2
          - name: Run IRIS Analysis
            uses: SonarSource/unified-dogfooding-actions/run-iris@v1
            with:
              primary_project_key: "SonarSource_speed-automations"
              primary_platform: "SQC-EU"
              shadow1_project_key: "SonarSource_speed-automations"
              shadow1_platform: "Next"
              shadow2_project_key: "SonarSource_speed-automations"
              shadow2_platform: "SQC-US"
